# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_iva_precioscertificados_ventacertificados'),
    ]

    operations = [
        migrations.CreateModel(
            name='conektaComision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
