# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_conektacomision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventacertificados',
            name='asociacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ventacertificados',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ventacertificados',
            name='ivaporcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='ventacertificados',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='ventacertificados',
            name='montoiva',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='ventacertificados',
            name='preciocertificado',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ventacertificados',
            name='tipocambio',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ventacertificados',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
